### ISSUE TITLE
simple flush

### ISSUE THREAD

**Issue by tissatussa** [joey-bednar/amelia#2]
i compiled your v0.12 source without any problem and the binary (only 48.1 Kb here) runs fine in CuteChess.
 
i figured out you can put a `fflush(stdout)` at the end of `printInfo()` and CuteChess shows its current pv line !

it seems your code is well made.
i set gcc-13 in the `Makefile` and i had only these few warnings, i guess they're easy to fix :

```c
$ make -j1
mkdir -p build/./src/
gcc-13 -I./src -MMD -MP -Wall -Wextra -O3 -march=native -c src/attack.c -o build/./src/attack.c.o -lm
mkdir -p build/./src/
gcc-13 -I./src -MMD -MP -Wall -Wextra -O3 -march=native -c src/search.c -o build/./src/search.c.o -lm
mkdir -p build/./src/
gcc-13 -I./src -MMD -MP -Wall -Wextra -O3 -march=native -c src/perft.c -o build/./src/perft.c.o -lm
mkdir -p build/./src/
gcc-13 -I./src -MMD -MP -Wall -Wextra -O3 -march=native -c src/utils.c -o build/./src/utils.c.o -lm
mkdir -p build/./src/
gcc-13 -I./src -MMD -MP -Wall -Wextra -O3 -march=native -c src/uci.c -o build/./src/uci.c.o -lm
src/uci.c: In function ‘startUCI’:
src/uci.c:252:9: warning: ignoring return value of ‘fgets’ declared with attribute ‘warn_unused_result’ [-Wunused-result]
  252 |         fgets(input, INPUTLEN, stdin);
      |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
mkdir -p build/./src/
gcc-13 -I./src -MMD -MP -Wall -Wextra -O3 -march=native -c src/main.c -o build/./src/main.c.o -lm
mkdir -p build/./src/
gcc-13 -I./src -MMD -MP -Wall -Wextra -O3 -march=native -c src/board.c -o build/./src/board.c.o -lm
mkdir -p build/./src/
gcc-13 -I./src -MMD -MP -Wall -Wextra -O3 -march=native -c src/eval.c -o build/./src/eval.c.o -lm
src/eval.c:6:12: warning: ‘pawnShield’ defined but not used [-Wunused-function]
    6 | static int pawnShield(BOARD_STATE *board, int color) {
      |            ^~~~~~~~~~
mkdir -p build/./src/
gcc-13 -I./src -MMD -MP -Wall -Wextra -O3 -march=native -c src/hash.c -o build/./src/hash.c.o -lm
mkdir -p build/./src/
gcc-13 -I./src -MMD -MP -Wall -Wextra -O3 -march=native -c src/init.c -o build/./src/init.c.o -lm
mkdir -p build/./src/
gcc-13 -I./src -MMD -MP -Wall -Wextra -O3 -march=native -c src/moves.c -o build/./src/moves.c.o -lm
mkdir -p build/./src/
gcc-13 -I./src -MMD -MP -Wall -Wextra -O3 -march=native -c src/tt.c -o build/./src/tt.c.o -lm
gcc-13 ./build/./src/attack.c.o ./build/./src/search.c.o ./build/./src/perft.c.o ./build/./src/utils.c.o ./build/./src/uci.c.o ./build/./src/main.c.o ./build/./src/board.c.o ./build/./src/eval.c.o ./build/./src/hash.c.o ./build/./src/init.c.o ./build/./src/moves.c.o ./build/./src/tt.c.o -o build/amelia  -lm
```

my notebook uses `bmi2` and `avx2`, can the `Makefile` be updated for that ?

**Comment by joey-bednar** [comment]
Thank you for your interest in the project.

- I have been meaning to rewrite the `Makefile` for a while but I forgot that I used the `march=native` flag which will make all of the releases not work on different systems. I will fix this and add support for different architectures.
- The fflush(stdout) I will have to investigate further before I implement it.
- I will fix the compilation warnings.

**Comment by tissatussa** [comment]
> ..The fflush(stdout) I will have to investigate further before I implement it..

did you know about this method ?
i'm not into C but i was familiar with flush .. probably you have more knowledge on this subject, so you also know disadvantages ? Will it slow things down ?

abou the Makefile : it's worth studying the Meson build system, i did recently and developed some standard template build file to compile most C packages .. however i'm still learning Meson, its doc looks good and complete but is confusing to many users .. i like it very much though .. its scripting is simple and nice, more consistend and elegant than cmake or make. Just saying ..

**Comment by tissatussa** [comment]
> ..my notebook uses bmi2 and avx2, can the Makefile be updated for that ?..

i think `-march=native` just suits the user CPU optimally, am i right ?
that's what i remember from recent investigation.

**Comment by joey-bednar** [comment]
Yes, that is correct. I used the `native` flag to optimize for my system while developing.

I'm not sure exactly how you're using `fflush` to view the PV in CuteChess. I would suspect the syscall will slow things down a little bit. Personally, if I want to view the engine output I use the `-debug` flag when I run my CuteChess.

I'm not comitted to using GNU Make but I would like to stick with it in the meantime. Maybe I will switch to an alternative in the future if there is a good justification for it.
