### ISSUE TITLE
poor time management

### ISSUE THREAD

**Issue by tissatussa** [joey-bednar/amelia#3]
in this 5m+3s game Amelia 0.12 had poor time management, and lost ..

![poor-time](https://github.com/user-attachments/assets/a60bb266-9e95-42a7-b799-4cbda98ae743)

why ?
you should certainly address that.

**Comment by joey-bednar** [comment]
Yes, this fix is on the agenda. I should probably start using Github issue tracking to indicate what features are in work.

**Comment by joey-bednar** [comment]
reopening for further testing
